### ISSUE TITLE
Exercicio Heranca

### ISSUE THREAD

**Issue by IsraelDeorce** [grupodobaralho/Zafari#10]
Alterar o projeto para ter dois tipos de usuário/Cliente
ClientePF - Pessoa Física - nome + cpf
ClientePJ - Pessoa Juridica - nome + cnp 

Código Cliente ???:
Professor, não entendi exatamente o que é para fazer com o "Código do Cliente"
Teria isso que ser gerado pela classe parent Cliente?

**Comment by aagustini** [comment]
Se notaste que tem herança envolvido notaste a pegadinnha. Veremos herança esta semana, sem este conceito deverá haver duplicação de código.
